const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const SITE='https://remyslab.com';
const YEAR='2026';

// Parses price_text values like "$179", "$17.99", "~$16" into a plain number for
// schema.org Offer.price. Several real lab notes have no price at all (None/'') --
// returns null in that case so the schema generator can skip the offers block
// entirely, rather than emit a broken/NaN price that just trades one Search
// Console error for another.
function parsePriceNumber(priceText){
  if(!priceText) return null;
  const match = String(priceText).replace(/~/g,'').match(/[\d.]+/);
  if(!match) return null;
  const n = parseFloat(match[0]);
  return Number.isFinite(n) ? n : null;
}

// Maps the real 3-state lab_result scale (approved / pass / still testing) to a
// schema.org rating. "testing" is explicitly NOT a completed verdict, so it
// returns null and the caller skips the Review block entirely for that note --
// presenting an in-progress test as a finished review would be dishonest, not
// just a schema technicality.
function labResultToRating(labResult){
  if(labResult==='approved') return 5;
  if(labResult==='pass') return 2;
  return null;
}
const GTM=`<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-TS4KTRPL');</script>
<!-- End Google Tag Manager -->`;
const GTM_BODY=`<!-- Google Tag Manager (noscript) --><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TS4KTRPL" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`;
const GENERATED='<!-- Generated by scripts/build-content.js -->';

function ensure(dir){fs.mkdirSync(path.join(ROOT,dir),{recursive:true});}
function esc(value=''){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function attr(value=''){return esc(value);}
function safeJson(obj){return JSON.stringify(obj).replace(/</g,'\\u003c');}
function validSlug(slug){return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug||'');}
function dateObj(value){const d=new Date((value||'1970-01-01')+'T12:00:00Z');return Number.isNaN(d.getTime())?new Date('1970-01-01T12:00:00Z'):d;}
function longDate(value){return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(dateObj(value));}
function shortDate(value){return new Intl.DateTimeFormat('en-US',{month:'numeric',day:'numeric',year:'2-digit',timeZone:'UTC'}).format(dateObj(value));}
function readDir(dir){const full=path.join(ROOT,dir);if(!fs.existsSync(full))return [];const now=new Date();return fs.readdirSync(full).filter(x=>x.endsWith('.json')).map(file=>{const data=JSON.parse(fs.readFileSync(path.join(full,file),'utf8'));if(!validSlug(data.slug))throw new Error(`Invalid slug in ${file}`);return data;}).filter(x=>x.published!==false).filter(x=>dateObj(x.date)<=now).sort((a,b)=>dateObj(b.date)-dateObj(a.date));}
function inline(text=''){
  let out=esc(text);
  out=out.replace(/\[([^\]]+)\]\(((?:https?:\/\/|\/)[^)]+)\)/g,(m,label,url)=>`<a href="${attr(url)}">${label}</a>`);
  out=out.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
  out=out.replace(/\*([^*]+)\*/g,'<em>$1</em>');
  return out;
}
function markdown(text=''){
  const lines=String(text).replace(/\r/g,'').split('\n');let html='',para=[],list=null;
  function flushPara(){if(para.length){html+=`<p>${inline(para.join(' '))}</p>`;para=[];}}
  function closeList(){if(list){html+=`</${list}>`;list=null;}}
  lines.forEach(line=>{
    if(!line.trim()){flushPara();closeList();return;}
    let m=line.match(/^(#{2,3})\s+(.+)$/);if(m){flushPara();closeList();const level=m[1].length;html+=`<h${level}>${inline(m[2])}</h${level}>`;return;}
    m=line.match(/^[-*]\s+(.+)$/);if(m){flushPara();if(list!=='ul'){closeList();html+='<ul>';list='ul';}html+=`<li>${inline(m[1])}</li>`;return;}
    m=line.match(/^\d+\.\s+(.+)$/);if(m){flushPara();if(list!=='ol'){closeList();html+='<ol>';list='ol';}html+=`<li>${inline(m[1])}</li>`;return;}
    para.push(line.trim());
  });flushPara();closeList();return html;
}
function rolodex(){return `<div class="partner-rolodex" id="partnerRolodex" aria-label="Active partner discount codes">
  <div class="rolodex-track" id="rolodexTrack">
    <div class="rolodex-slide is-active" aria-hidden="false">
      <img class="rolodex-logo" src="/assets/logos/pack-leashes-logo.jpg" alt="" width="22" height="22" loading="eager" decoding="async"/>
      <span class="rolodex-copy"><strong>Pack Leashes</strong> &middot; 20% off with <code>REMYSLAB20</code></span>
      <a class="rolodex-btn affiliate-link" href="https://packleashes.com/discount/REMYSLAB20?redirect=/" target="_blank" rel="nofollow sponsored" data-product="Pack Leashes" data-category="partner_store" data-result="current_partner" data-placement="rolodex" data-discount="REMYSLAB20" data-network="Pack Leashes">Visit site</a>
    </div>
    <div class="rolodex-slide" aria-hidden="true">
      <img class="rolodex-logo" src="/assets/logos/brooks-and-roo-logo.jpg" alt="" width="22" height="22" loading="lazy" decoding="async"/>
      <span class="rolodex-copy"><strong>Brooks &amp; Roo</strong> &middot; 15% off with <code>REMYSLAB15</code></span>
      <a class="rolodex-btn affiliate-link" href="https://www.brooksandroo.com/discount/REMYSLAB15?ref=REMYSLAB15" target="_blank" rel="nofollow sponsored" data-product="Brooks &amp; Roo" data-category="partner_store" data-result="current_partner" data-placement="rolodex" data-discount="REMYSLAB15" data-network="Brooks &amp; Roo">Visit site</a>
    </div>
    <div class="rolodex-slide" aria-hidden="true">
      <img class="rolodex-logo" src="/assets/logos/sniff-and-bark-logo.webp" alt="" width="22" height="22" loading="lazy" decoding="async"/>
      <span class="rolodex-copy"><strong>Sniff &amp; Bark</strong> &middot; 20% off with <code>REMYSLAB20</code></span>
      <a class="rolodex-btn affiliate-link" href="https://www.sniffandbark.com.co/discount/REMYSLAB20?redirect=/" target="_blank" rel="nofollow sponsored" data-product="Sniff &amp; Bark" data-category="partner_store" data-result="current_partner" data-placement="rolodex" data-discount="REMYSLAB20" data-network="Sniff &amp; Bark">Visit site</a>
    </div>
    <div class="rolodex-slide" aria-hidden="true">
      <img class="rolodex-logo" src="/assets/logos/woof-logo.webp" alt="" width="22" height="22" loading="lazy" decoding="async"/>
      <span class="rolodex-copy"><strong>Woof</strong> &middot; 10% off with <code>REMYSLAB10</code></span>
      <a class="rolodex-btn affiliate-link" href="https://mywoof.com/discount/REMYSLAB10" target="_blank" rel="nofollow sponsored" data-product="Woof" data-category="partner_store" data-result="current_partner" data-placement="rolodex" data-discount="REMYSLAB10" data-network="Woof">Visit site</a>
    </div>
    <div class="rolodex-slide" aria-hidden="true">
      <img class="rolodex-logo" src="/assets/logos/sodapup-logo.webp" alt="" width="22" height="22" loading="lazy" decoding="async"/>
      <span class="rolodex-copy"><strong>SodaPup</strong> &middot; 10% off with <code>JOSH</code></span>
      <a class="rolodex-btn affiliate-link" href="https://sodapup.com/?ref=remyslab" target="_blank" rel="nofollow sponsored" data-product="SodaPup" data-category="partner_store" data-result="current_partner" data-placement="rolodex" data-discount="JOSH" data-network="SodaPup">Visit site</a>
    </div>
  </div>
  <button type="button" class="rolodex-arrow rolodex-prev" id="rolodexPrev" aria-label="Previous partner">&larr;</button>
  <button type="button" class="rolodex-arrow rolodex-next" id="rolodexNext" aria-label="Next partner">&rarr;</button>
  <div class="rolodex-dots" id="rolodexDots" role="tablist" aria-label="Select partner slide"></div>
</div>`;}
function nav(active){return `${rolodex()}<nav class="site-nav"><div class="nav-inner"><a class="nav-logo" href="/"><img src="/assets/icons/nav-icon.png" alt="Remy's Lab" width="30" height="30"><span>Remy's Lab</span></a><div class="nav-tabs"><a class="nav-tab${active==='compare'?' active':''}" href="/">Compare</a><a class="nav-tab${active==='codes'?' active':''}" href="/codes/">Codes</a><a class="nav-tab${active==='notes'?' active':''}" href="/blog/">Lab Notes</a></div></div></nav>`;}
function footer(){return `<footer><div class="footer-inner"><div class="footer-brand">Remy's Lab</div><div class="footer-desc">Compare dog gear prices, grab codes, and read honest test notes from @remy.lab on TikTok.</div><div class="footer-links"><a href="/">Compare</a><a href="/codes/">Codes</a><a href="/blog/">Lab Notes</a><a href="/vendors/">Vendors</a><a href="https://www.tiktok.com/@remy.lab" target="_blank" rel="noopener">TikTok</a><a href="/disclaimer.html">Disclosure</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></div><div class="footer-bottom">© ${YEAR} Remy's Lab · Some links may be affiliate links · Remy is a real dog.</div></div></footer>`;}
function head({title,description,canonical,type='website',schema=[]}){return `${GTM}<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${esc(title)}</title><meta name="description" content="${attr(description)}"><link rel="canonical" href="${attr(canonical)}"><link rel="icon" type="image/png" href="/assets/icons/favicon.png"><meta name="theme-color" content="#f5f8fc"><meta property="og:type" content="${attr(type)}"><meta property="og:site_name" content="Remy's Lab"><meta property="og:title" content="${attr(title)}"><meta property="og:description" content="${attr(description)}"><meta property="og:url" content="${attr(canonical)}"><meta property="og:image" content="${SITE}/assets/logos/og-image.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${attr(title)}"><meta name="twitter:description" content="${attr(description)}"><meta name="twitter:image" content="${SITE}/assets/logos/og-image.jpg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&family=Roboto+Mono:wght@500;600&family=Source+Sans+3:wght@400;500;600;700;800&display=swap"><link rel="stylesheet" href="/assets/css/content.css"><style>.partner-rolodex{position:fixed;top:0;left:0;right:0;z-index:300;height:52px;background:linear-gradient(135deg,#173b61 0%,#245f93 100%);display:flex;align-items:center;overflow:hidden}.rolodex-track{position:relative;flex:1 1 auto;height:100%;overflow:hidden}.rolodex-slide{position:absolute;inset:0;display:flex;align-items:center;gap:10px;padding:0 48px;opacity:0;pointer-events:none;transition:opacity .35s ease}.rolodex-slide.is-active{opacity:1;pointer-events:auto}.rolodex-logo{flex:0 0 auto;width:28px;height:28px;border-radius:7px;object-fit:contain;background:#fff;padding:3px}.rolodex-copy{flex:1 1 auto;min-width:0;font-size:13px;color:#fff;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rolodex-copy strong{font-weight:800}.rolodex-copy code{background:rgba(255,255,255,.18);border-radius:5px;padding:2px 7px;font-size:12px}.rolodex-btn{flex:0 0 auto;font-size:12px;font-weight:800;color:#173b61;background:#fff8e3;border-radius:999px;padding:6px 13px;text-decoration:none;white-space:nowrap}.rolodex-arrow{flex:0 0 auto;width:28px;height:28px;border:0;background:rgba(255,255,255,.14);color:#fff;border-radius:999px;font-size:13px;cursor:pointer;display:flex;align-items:center;justify-content:center}.rolodex-prev{margin-left:8px}.rolodex-next{margin-right:6px}.rolodex-dots{position:absolute;right:58px;top:50%;transform:translateY(-50%);display:flex;gap:5px}.rolodex-dot{width:6px;height:6px;border-radius:999px;background:rgba(255,255,255,.35);border:0;padding:0;cursor:pointer}.rolodex-dot.is-active{background:#fff}@media(max-width:560px){.rolodex-slide{padding:0 14px;gap:8px}.rolodex-dots{display:none}.rolodex-btn{padding:5px 10px}}</style>${schema.map(x=>`<script type="application/ld+json">${safeJson(x)}</script>`).join('')}`;}
function resultLabel(value){return value==='testing'?'Still testing':value==='pass'?'Not for us':'Remy approved';}
function categorySlug(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function cleanGenerated(folder){const full=path.join(ROOT,folder);ensure(folder);for(const name of fs.readdirSync(full)){if(name==='index.html'||!name.endsWith('.html'))continue;const file=path.join(full,name);const body=fs.readFileSync(file,'utf8');if(body.includes(GENERATED))fs.unlinkSync(file);}}
function trackingAttrs(note,placement){return `data-product="${attr(note.product_name)}" data-category="${attr(categorySlug(note.category))}" data-result="${attr(note.lab_result)}" data-placement="${attr(placement)}" data-discount="${attr(note.discount_code||'')}" data-network="${attr(note.affiliate_network||'')}"`;}
function cta(note,placement){if(!note.affiliate_url)return '';return `<div class="buy-box"><div><strong>${esc(note.product_name)}${note.price_text?' · '+esc(note.price_text):''}</strong><p>${esc(note.affiliate_network||'Partner link')}</p></div><a class="buy-btn affiliate-link" href="${attr(note.affiliate_url)}" target="_blank" rel="nofollow sponsored" ${trackingAttrs(note,placement)}>${esc(note.button_text||'Visit brand site')}</a></div>`;}
function codeBox(note){if(!note.discount_code)return '';return `<div class="code-box"><div><strong>Use code ${esc(note.discount_code)}</strong><p>Grab the code if you buy.</p></div><button class="copy-btn coupon-copy" type="button" data-code="${attr(note.discount_code)}" data-product="${attr(note.product_name)}" data-category="${attr(categorySlug(note.category))}" data-placement="lab_note_code">Grab code</button></div>`;}
function faqHtml(faqs=[]){if(!faqs.length)return '';return `<section class="faq"><h2>Common questions</h2>${faqs.map(x=>`<div class="faq-item"><p class="faq-q">${esc(x.question)}</p><p class="faq-a">${esc(x.answer)}</p></div>`).join('')}</section>`;}
function faqSchema(faqs=[]){return faqs.length?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(x=>({"@type":"Question",name:x.question,acceptedAnswer:{"@type":"Answer",text:x.answer}}))}:null;}
function breadcrumb(items){return {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.name,item:x.item}))};}
function renderLabNote(note){
 const canonical=`${SITE}/blog/${note.slug}`;const productImage=note.image_url?(String(note.image_url).startsWith('http')?note.image_url:`${SITE}${note.image_url}`):undefined;
 // Real offers/review data, not fabricated: priceNum comes from the actual price_text
 // field (several notes genuinely have no price -- offers is omitted for those rather
 // than emit a broken price). rating comes from the real 3-state lab_result scale;
 // "still testing" notes correctly get no review block at all, since presenting an
 // unfinished test as a completed review would be dishonest.
 const priceNum=parsePriceNumber(note.price_text);
 const ratingValue=labResultToRating(note.lab_result);
 const productSchema={"@type":"Product",name:note.product_name,brand:note.brand?{"@type":"Brand",name:note.brand.trim()}:undefined,image:productImage,
   ...(priceNum!=null?{offers:{"@type":"Offer",price:priceNum,priceCurrency:"USD",url:note.affiliate_url,availability:"https://schema.org/InStock"}}:{}),
   ...(ratingValue!=null?{review:{"@type":"Review",reviewRating:{"@type":"Rating",ratingValue,bestRating:5},author:{"@type":"Organization",name:"Remy's Lab"},reviewBody:note.verdict_text,datePublished:note.date},
       aggregateRating:{"@type":"AggregateRating",ratingValue,bestRating:5,reviewCount:1}}:{})};
 const schemas=[{"@context":"https://schema.org","@type":"Article",headline:note.title,description:note.description,datePublished:note.date,dateModified:note.date,image:productImage,author:{"@type":"Organization",name:"Remy's Lab",url:SITE},publisher:{"@type":"Organization",name:"Remy's Lab",url:SITE,logo:{"@type":"ImageObject",url:`${SITE}/assets/logos/og-image.jpg`}},about:productSchema,mainEntityOfPage:{"@type":"WebPage","@id":canonical}},breadcrumb([{name:'Home',item:SITE+'/'},{name:'Lab Notes',item:SITE+'/blog/'},{name:note.title,item:canonical}])];const fq=faqSchema(note.faqs);if(fq)schemas.push(fq);
 const productPhoto=note.image_url?`<figure class="product-photo"><img src="${attr(note.image_url)}" alt="${attr(note.image_alt||note.product_name)}" loading="eager" decoding="async"></figure>`:'';
 const surfaces=(note.surfaces||[]).length?`<div class="surface-list">${note.surfaces.map(x=>`<div class="surface-item"><span class="surface-marker" aria-hidden="true"></span><div><div class="surface-name">${esc(x.name)}</div><div class="surface-note">${esc(x.note)}</div></div></div>`).join('')}</div>`:'';
 return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({title:`${note.title} | Remy's Lab`,description:note.description,canonical,type:'article',schema:schemas})}</head><body>${GTM_BODY}${nav('notes')}<main><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="/blog/">Lab Notes</a><span>›</span><span>${esc(note.product_name)}</span></nav><div class="post-meta"><span class="meta-pill">${esc(note.category)}</span><span class="meta-pill result">${esc(resultLabel(note.lab_result))}</span><span class="meta-pill">${esc(longDate(note.date))}</span></div><h1>${esc(note.title)}</h1><p class="post-lede">${esc(note.lede)}</p>${productPhoto}<div class="verdict"><div><span class="verdict-label">Test notes</span><strong>${esc(note.verdict_title)}</strong><p>${esc(note.verdict_text)}</p></div></div>${cta(note,'blog_post_top')}${codeBox(note)}<div class="post-body"><h2>What we tested</h2>${markdown(note.what_we_tested)}${surfaces}<h2>What worked</h2>${markdown(note.what_worked)}<h2>What did not work</h2>${markdown(note.what_didnt_work)}<h2>Remy's take</h2>${markdown(note.remys_take)}<h2>Worth buying?</h2>${markdown(note.worth_buying)}</div>${cta(note,'blog_post_bottom')}${faqHtml(note.faqs)}<p class="disclosure">Some links are affiliate links. If you buy through one, Remy's Lab may earn a small commission at no extra cost to you. That does not change what gets tested or what we say. <a href="/disclaimer.html">Full disclosure</a>.</p></div></main>${footer()}<script src="/assets/js/affiliate-tracking.js"></script><script src="/assets/js/rolodex.js"></script></body></html>`;
}
function renderBlogIndex(notes,guides){
 const cats=['Walk Gear','Toys','Treats','Cleaning','Health','Accessories','Everyday Dog Life'];
 const noteCards=notes.map(n=>({date:n.date,html:`<a class="note-row" href="/blog/${attr(n.slug)}" data-filter-card data-type="review" data-category="${attr(categorySlug(n.category))}" data-date="${attr(n.date)}" data-search="${attr([n.title,n.product_name,n.category,n.card_summary].join(' '))}"><div class="note-row-meta"><span class="note-row-cat">${esc(n.category)}</span><span class="note-row-date">${esc(shortDate(n.date))}</span></div><strong class="note-row-title">${esc(n.product_name)}</strong><p class="note-row-summary">${esc(n.card_summary)}</p><span class="note-row-badge badge-${attr(n.lab_result||'approved')}">${esc(resultLabel(n.lab_result))}</span></a>`}));
 const guideCards=guides.map(g=>({date:g.date,html:`<a class="guide-card" href="/guides/${attr(g.slug)}" data-filter-card data-type="guide" data-category="${attr(categorySlug(g.category))}" data-date="${attr(g.date)}" data-search="${attr([g.title,g.category,g.card_summary].join(' '))}"><div class="guide-card-meta"><span class="guide-cat">${esc(g.category)} · Guide</span><span class="guide-date">${esc(shortDate(g.date))}</span></div><h2>${esc(g.title)}</h2><p>${esc(g.card_summary)}</p><span class="read">Read the guide →</span></a>`}));
 const cards=[...noteCards,...guideCards].sort((a,b)=>dateObj(b.date)-dateObj(a.date)).map(x=>x.html).join('');
 const total=notes.length+guides.length;
 return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({title:`Lab Notes | Remy's Lab`,description:'Product reviews and buying guides from Remy\u2019s Lab. Honest test notes, no fake rankings.',canonical:SITE+'/blog/'})}</head><body>${GTM_BODY}${nav('notes')}<main><section class="clipboard"><div class="clipboard-paper"><div class="hero-inner"><div class="eyebrow">Remy's Lab · Test reports &amp; guides</div><h1>Lab Notes</h1><p class="hero-sub">Products Remy has actually used, plus buying guides when a question needs more than one product to answer. Honest notes, no fake rankings.</p><div class="hero-stats"><span class="hero-stat">${notes.length} ${notes.length===1?'review':'reviews'} · ${guides.length} ${guides.length===1?'guide':'guides'}</span><span class="hero-pill"><i></i> ${total} ${total===1?'entry':'entries'} filed</span></div></div></div></section><section class="controls"><div class="controls-inner"><div class="search-row"><svg width="15" height="15" viewBox="0 0 15 15" fill="none"><path d="M10 6.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zm-.666 3.42a4.5 4.5 0 1 1 .707-.707l2.873 2.872a.5.5 0 1 1-.707.707L9.334 9.92z" fill="currentColor"/></svg><input class="search-input" id="contentSearch" type="search" placeholder="Search lab notes and guides..." aria-label="Search lab notes and guides"></div><div class="filter-bar type-filter-bar"><button class="filter-pill type-pill active" data-type-filter="all">Everything</button><button class="filter-pill type-pill" data-type-filter="review">Reviews only</button><button class="filter-pill type-pill" data-type-filter="guide">Guides only</button></div><div class="filter-bar"><button class="filter-pill active" data-filter="all">All topics</button>${cats.map(c=>`<button class="filter-pill" data-filter="${categorySlug(c)}">${esc(c)}</button>`).join('')}</div></div></section><section class="note-list"><div class="results-row"><p class="results-label" id="resultsLabel"></p><label class="sort-label" for="sortSelect">Sort<select id="sortSelect" aria-label="Sort by date"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div>${cards}<div class="empty-state" id="emptyState" style="display:none">No matching results yet. Remy's working on it.</div></section></main>${footer()}<script src="/assets/js/content-filters.js"></script><script src="/assets/js/rolodex.js"></script></body></html>`;
}
function renderGuideIndex(guides){const cats=['Cleaning','Walk Gear','Toys','Treats','Everyday Dog Life'];const cards=guides.map(g=>`<a class="guide-card" href="/guides/${attr(g.slug)}" data-filter-card data-category="${attr(categorySlug(g.category))}" data-search="${attr([g.title,g.category,g.card_summary].join(' '))}"><span class="guide-cat">${esc(g.category)} guide</span><h2>${esc(g.title)}</h2><p>${esc(g.card_summary)}</p><span class="read">Read the guide →</span></a>`).join('');return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({title:`Dog Owner Guides | Remy's Lab`,description:'Useful dog owner guides from Remy’s Lab, with simple answers, honest notes, and links to related products we have actually tested.',canonical:SITE+'/guides/'})}</head><body>${GTM_BODY}${nav('notes')}<main><section class="clipboard"><div class="clipboard-paper"><div class="hero-inner"><div class="eyebrow">Remy's Lab · Dog owner answers</div><h1>Dog Owner Guides</h1><p class="hero-sub">Useful answers for common dog owner problems. Related Lab Notes only when we actually tested something.</p><div class="hero-stats"><span class="hero-stat">${guides.length} ${guides.length===1?'guide':'guides'} filed</span><span class="hero-pill"><i></i> Practical notes</span></div></div></div></section><section class="controls"><div class="controls-inner"><div class="search-row"><svg width="15" height="15" viewBox="0 0 15 15" fill="none"><path d="M10 6.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zm-.666 3.42a4.5 4.5 0 1 1 .707-.707l2.873 2.872a.5.5 0 1 1-.707.707L9.334 9.92z" fill="currentColor"/></svg><input class="search-input" id="contentSearch" type="search" placeholder="Search dog owner guides..." aria-label="Search guides"></div><div class="filter-bar"><button class="filter-pill active" data-filter="all">All Guides</button>${cats.map(c=>`<button class="filter-pill" data-filter="${categorySlug(c)}">${esc(c)}</button>`).join('')}</div></div></section><section class="guide-grid"><p class="results-label" id="resultsLabel"></p>${cards}<div class="empty-state" id="emptyState" style="${guides.length?'display:none':''}">${guides.length?'No matching guides yet.':'The guide shelf is ready. Publish the first guide through the CMS when you are ready.'}</div></section></main>${footer()}<script src="/assets/js/content-filters.js"></script><script src="/assets/js/rolodex.js"></script></body></html>`;}
function renderGuide(guide,notesBySlug){const canonical=`${SITE}/guides/${guide.slug}`;const schemas=[{"@context":"https://schema.org","@type":"Article",headline:guide.title,description:guide.description,datePublished:guide.date,dateModified:guide.date,author:{"@type":"Organization",name:"Remy's Lab",url:SITE},publisher:{"@type":"Organization",name:"Remy's Lab",url:SITE,logo:{"@type":"ImageObject",url:`${SITE}/assets/logos/og-image.jpg`}},mainEntityOfPage:{"@type":"WebPage","@id":canonical}},breadcrumb([{name:'Home',item:SITE+'/'},{name:'Lab Notes',item:SITE+'/blog/'},{name:guide.title,item:canonical}])];const fq=faqSchema(guide.faqs);if(fq)schemas.push(fq);const related=(guide.related_lab_notes||[]).map(slug=>notesBySlug[slug]).filter(Boolean);const relatedHtml=related.length?`<section class="related"><h2>Related Lab Notes</h2><div class="related-grid">${related.map(n=>`<a class="related-card" href="/blog/${attr(n.slug)}"><strong>${esc(n.product_name)}</strong><p>${esc(n.card_summary)}</p></a>`).join('')}</div></section>`:'';return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({title:`${guide.title} | Remy's Lab`,description:guide.description,canonical,type:'article',schema:schemas})}</head><body>${GTM_BODY}${nav('notes')}<main><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="/blog/">Lab Notes</a><span>›</span><span>${esc(guide.title)}</span></nav><div class="post-meta"><span class="meta-pill">${esc(guide.category)} guide</span><span class="meta-pill">${esc(longDate(guide.date))}</span></div><h1>${esc(guide.title)}</h1><div class="quick-answer"><strong>Quick answer</strong><p>${esc(guide.quick_answer)}</p></div><div class="post-body">${markdown(guide.body)}</div>${relatedHtml}${faqHtml(guide.faqs)}<p class="disclosure">Some related Lab Notes may include affiliate links. If you buy through one, Remy's Lab may earn a small commission at no extra cost to you. <a href="/disclaimer.html">Full disclosure</a>.</p></div></main>${footer()}<script src="/assets/js/rolodex.js"></script></body></html>`;}
function write(rel,body){const full=path.join(ROOT,rel);ensure(path.dirname(rel));fs.writeFileSync(full,body,'utf8');}
function sitemap(notes,guides){const today=new Date().toISOString().slice(0,10);const pages=[['/',today,'weekly','1.0'],['/codes/',today,'weekly','0.8'],['/blog/',notes[0]?.date||today,'weekly','0.9'],...notes.map(n=>[`/blog/${n.slug}`,n.date,'monthly','0.8']),...guides.map(g=>[`/guides/${g.slug}`,g.date,'monthly','0.8']),['/privacy.html','2026-05-29','yearly','0.3'],['/terms.html','2026-05-29','yearly','0.3'],['/disclaimer.html','2026-05-29','yearly','0.3']];return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(([url,lastmod,freq,priority])=>`  <url><loc>${SITE}${url}</loc><lastmod>${lastmod}</lastmod><changefreq>${freq}</changefreq><priority>${priority}</priority></url>`).join('\n')}
</urlset>
`;}
function llms(notes,guides){return `# Remy's Lab

> Dog gear price comparison, discount codes, and real test notes from a yellow Lab.

Remy's Lab is a TikTok-connected dog product testing brand built around Remy, a yellow Labrador. The site helps dog owners compare dog gear prices by category, grab active partner codes, and read honest test notes when Remy has actually used a product.

## Pages

- [Compare dog gear prices](${SITE}/): Live dog gear prices from tracked brand stores, grouped by category and sorted low to high. This is a price browser, not a Remy-tested endorsement list.
- [Codes](${SITE}/codes/): Active Remy's Lab partner and ambassador codes.
- [Lab Notes](${SITE}/blog/): Written notes after Remy actually uses a product, plus dog owner buying guides.

## How Remy's Lab separates things

- Compare: tracked prices and codes from brand stores.
- Lab Notes: products Remy has actually used, products still being tested, and honest dog owner guides.
- Codes: current partner and ambassador discounts Josh can share.

## Lab Notes

${notes.map(n=>`- [${n.title}](${SITE}/blog/${n.slug}): ${n.card_summary}`).join('\n')||'- No Lab Notes are currently published.'}

## Dog Owner Guides

${guides.map(g=>`- [${g.title}](${SITE}/guides/${g.slug}): ${g.card_summary}`).join('\n')||'- No Dog Owner Guides are currently published.'}

## Current partner brands

- Pack Leashes: Current partner. Use code REMYSLAB20 for 20% off at packleashes.com.
- Brooks & Roo: Current partner. Use code REMYSLAB15 for 15% off sitewide at brooksandroo.com.

## Social

- TikTok: https://www.tiktok.com/@remy.lab

## Affiliate disclosure

Some links may be affiliate links. If a visitor uses one, Remy's Lab may earn a commission. That does not change which products are listed or what gets written about them.
`;}
function main(){ensure('blog');ensure('guides');cleanGenerated('blog');cleanGenerated('guides');const notes=readDir('content/lab-notes');const guides=readDir('content/guides');const notesBySlug=Object.fromEntries(notes.map(n=>[n.slug,n]));notes.forEach(n=>write(`blog/${n.slug}.html`,renderLabNote(n)));guides.forEach(g=>write(`guides/${g.slug}.html`,renderGuide(g,notesBySlug)));write('blog/index.html',renderBlogIndex(notes,guides));write('sitemap.xml',sitemap(notes,guides));write('llms.txt',llms(notes,guides));console.log(`Built ${notes.length} Lab Notes and ${guides.length} Dog Owner Guides into one merged /blog/ feed.`);}
main();
