const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SITE = 'https://remyslab.com';
const YEAR = '2026';
const TODAY = '2026-06-19';
const GTM = `<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-TS4KTRPL');</script>
<!-- End Google Tag Manager -->`;
const GTM_BODY = `<!-- Google Tag Manager (noscript) --><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TS4KTRPL" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`;
const GENERATED = '<!-- Generated by scripts/build-content.js -->';

function ensure(dir) { fs.mkdirSync(path.join(ROOT, dir), { recursive: true }); }
function esc(value = '') { return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
function attr(value = '') { return esc(value); }
function safeJson(obj) { return JSON.stringify(obj).replace(/</g, '\\u003c'); }
function validSlug(slug) { return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug || ''); }
function dateObj(value) { const d = new Date((value || '1970-01-01') + 'T12:00:00Z'); return Number.isNaN(d.getTime()) ? new Date('1970-01-01T12:00:00Z') : d; }
function longDate(value) { return new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(dateObj(value)); }
function shortDate(value) { return new Intl.DateTimeFormat('en-US', { month: 'numeric', day: 'numeric', year: '2-digit', timeZone: 'UTC' }).format(dateObj(value)); }
function categorySlug(value) { return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function firstDate(items) { return items[0]?.date || TODAY; }
function publicUrl(url) { return url && url.startsWith('/') ? SITE + url : url; }
function cleanArray(value) { return Array.isArray(value) ? value : []; }

function readDir(dir) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) return [];
  return fs.readdirSync(full)
    .filter((x) => x.endsWith('.json'))
    .map((file) => {
      const data = JSON.parse(fs.readFileSync(path.join(full, file), 'utf8'));
      if (!validSlug(data.slug)) throw new Error(`Invalid slug in ${file}`);
      return data;
    })
    .filter((x) => x.published !== false)
    .sort((a, b) => {
      const order = (a.sort_order ?? 999) - (b.sort_order ?? 999);
      if (order) return order;
      const dateSort = dateObj(b.date) - dateObj(a.date);
      if (dateSort) return dateSort;
      return String(a.title || a.brand_name || '').localeCompare(String(b.title || b.brand_name || ''));
    });
}

function inline(text = '') {
  let out = esc(text);
  out = out.replace(/\[([^\]]+)\]\(((?:https?:\/\/|\/)[^)]+)\)/g, (m, label, url) => `<a href="${attr(url)}">${label}</a>`);
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  return out;
}

function markdown(text = '') {
  const lines = String(text).replace(/\r/g, '').split('\n');
  let html = '';
  let para = [];
  let list = null;
  function flushPara() { if (para.length) { html += `<p>${inline(para.join(' '))}</p>`; para = []; } }
  function closeList() { if (list) { html += `</${list}>`; list = null; } }
  lines.forEach((line) => {
    if (!line.trim()) { flushPara(); closeList(); return; }
    let m = line.match(/^(#{2,3})\s+(.+)$/);
    if (m) { flushPara(); closeList(); const level = m[1].length; html += `<h${level}>${inline(m[2])}</h${level}>`; return; }
    m = line.match(/^[-*]\s+(.+)$/);
    if (m) { flushPara(); if (list !== 'ul') { closeList(); html += '<ul>'; list = 'ul'; } html += `<li>${inline(m[1])}</li>`; return; }
    m = line.match(/^\d+\.\s+(.+)$/);
    if (m) { flushPara(); if (list !== 'ol') { closeList(); html += '<ol>'; list = 'ol'; } html += `<li>${inline(m[1])}</li>`; return; }
    para.push(line.trim());
  });
  flushPara();
  closeList();
  return html;
}

function nav(active) {
  const items = [
    ['links', '/', 'Links'],
    ['notes', '/blog/', 'Lab Notes'],
    ['partners', '/partners/', 'Partners'],
    ['faq', '/dog-product-faq/', 'FAQ'],
    ['tiktok', 'https://www.tiktok.com/@remy.lab', 'TikTok'],
  ];
  return `<nav class="site-nav"><div class="nav-inner"><a class="nav-logo" href="/"><img src="/assets/icons/remys-lab-dog-scientist-icon-transparent-v2.png" alt="Remy's Lab" width="30" height="30"><span>Remy's Lab</span></a><div class="nav-tabs">${items.map(([key, href, label]) => `<a class="nav-tab${active === key ? ' active' : ''}" href="${href}"${key === 'tiktok' ? ' target="_blank" rel="noopener"' : ''}>${label}</a>`).join('')}</div></div></nav>`;
}

function footer() {
  return `<footer><div class="footer-inner"><div class="footer-brand">Remy's Lab</div><div class="footer-desc">Dog products tested by an actual Lab 🧪, test notes, partner links, and discount codes from @remy.lab on TikTok.</div><div class="footer-links"><a href="/">Home</a><a href="/partners/">Partners</a><a href="/blog/">Lab Notes</a><a href="/dog-product-faq/">Dog Product FAQ</a><a href="/guides/">Guides</a><a href="https://www.tiktok.com/@remy.lab" target="_blank" rel="noopener">TikTok</a><a href="/disclaimer.html">Disclosure</a><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></div><div class="footer-bottom">© ${YEAR} Remy's Lab. Some links may be affiliate links. Remy is a real dog.</div></div></footer>`;
}

function head({ title, description, canonical, type = 'website', schema = [] }) {
  return `${GTM}<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${esc(title)}</title><meta name="description" content="${attr(description)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="${attr(canonical)}"><link rel="icon" type="image/png" href="/assets/icons/favicon-remy-scientist-transparent-v2.png"><meta name="theme-color" content="#f7f5ef"><meta property="og:type" content="${attr(type)}"><meta property="og:site_name" content="Remy's Lab"><meta property="og:title" content="${attr(title)}"><meta property="og:description" content="${attr(description)}"><meta property="og:url" content="${attr(canonical)}"><meta property="og:image" content="${SITE}/assets/logos/remys-lab-logo-science-dog-transparent-v2.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${attr(title)}"><meta name="twitter:description" content="${attr(description)}"><meta name="twitter:image" content="${SITE}/assets/logos/remys-lab-logo-science-dog-transparent-v2.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,600;0,9..40,700;0,9..40,800&family=DM+Mono:wght@400;500&family=Caveat:wght@600&display=swap"><link rel="stylesheet" href="/assets/css/content.css">${schema.filter(Boolean).map((x) => `<script type="application/ld+json">${safeJson(x)}</script>`).join('')}`;
}

function resultLabel(value) {
  return value === 'testing' ? '🧪 Still testing' : value === 'pass' ? '↩ Not for us' : '🦴 Remy approved';
}

function cleanGeneratedTree(folder) {
  const full = path.join(ROOT, folder);
  if (!fs.existsSync(full)) return;
  function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      const current = path.join(dir, name);
      const stat = fs.statSync(current);
      if (stat.isDirectory()) {
        walk(current);
        if (fs.existsSync(current) && fs.readdirSync(current).length === 0) fs.rmdirSync(current);
      } else if (name.endsWith('.html')) {
        const body = fs.readFileSync(current, 'utf8');
        if (body.includes(GENERATED)) fs.unlinkSync(current);
      }
    }
  }
  walk(full);
}

function write(rel, body) {
  const full = path.join(ROOT, rel);
  ensure(path.dirname(rel));
  fs.writeFileSync(full, body, 'utf8');
}

function breadcrumb(items) {
  return { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: items.map((x, i) => ({ '@type': 'ListItem', position: i + 1, name: x.name, item: x.item })) };
}

function faqSchema(faqs = []) {
  const clean = cleanArray(faqs).filter((x) => x.question && x.answer);
  return clean.length ? { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: clean.map((x) => ({ '@type': 'Question', name: x.question, acceptedAnswer: { '@type': 'Answer', text: x.answer } })) } : null;
}

function faqHtml(faqs = []) {
  const clean = cleanArray(faqs).filter((x) => x.question && x.answer);
  if (!clean.length) return '';
  return `<section class="faq"><h2>Common questions</h2>${clean.map((x) => `<div class="faq-item"><p class="faq-q">${esc(x.question)}</p><p class="faq-a">${esc(x.answer)}</p></div>`).join('')}</section>`;
}

function trackingAttrs(note, placement) {
  return `data-product="${attr(note.product_name)}" data-category="${attr(categorySlug(note.category))}" data-result="${attr(note.lab_result)}" data-placement="${attr(placement)}" data-discount="${attr(note.discount_code || '')}" data-network="${attr(note.affiliate_network || '')}"`;
}

function partnerTrackingAttrs(partner, placement) {
  return `data-product="${attr(partner.brand_name)}" data-category="partner_store" data-result="current_partner" data-placement="${attr(placement)}" data-discount="${attr(partner.coupon_code || '')}" data-network="${attr(partner.brand_name)}"`;
}

function cta(note, placement) {
  if (!note.affiliate_url) return '';
  return `<div class="buy-box"><div><strong>${esc(note.product_name)}${note.price_text ? ' · ' + esc(note.price_text) : ''}</strong><p>${esc(note.affiliate_network || 'Partner link')}</p></div><a class="buy-btn affiliate-link" href="${attr(note.affiliate_url)}" target="_blank" rel="nofollow sponsored" ${trackingAttrs(note, placement)}>${esc(note.button_text || 'Visit brand site')}</a></div>`;
}

function codeBox(note) {
  if (!note.discount_code) return '';
  return `<div class="code-box"><div><strong>Use code ${esc(note.discount_code)}</strong><p>Grab the code if you buy.</p></div><button class="copy-btn coupon-copy" type="button" data-code="${attr(note.discount_code)}" data-product="${attr(note.product_name)}" data-category="${attr(categorySlug(note.category))}" data-placement="lab_note_code">Grab code</button></div>`;
}

function renderLabNote(note) {
  const canonical = `${SITE}/blog/${note.slug}.html`;
  const productImage = note.image_url ? `${SITE}${note.image_url}` : undefined;
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: note.title, description: note.description, datePublished: note.date, dateModified: note.date, image: productImage, author: { '@type': 'Organization', name: "Remy's Lab", url: SITE }, publisher: { '@type': 'Organization', name: "Remy's Lab", url: SITE, logo: { '@type': 'ImageObject', url: `${SITE}/assets/logos/remys-lab-logo-science-dog-transparent-v2.png` } }, about: { '@type': 'Product', name: note.product_name, brand: note.brand ? { '@type': 'Brand', name: note.brand } : undefined, image: productImage }, mainEntityOfPage: { '@type': 'WebPage', '@id': canonical } },
    breadcrumb([{ name: 'Home', item: SITE + '/' }, { name: 'Lab Notes', item: SITE + '/blog/' }, { name: note.title, item: canonical }]),
    faqSchema(note.faqs),
  ];
  const productPhoto = note.image_url ? `<figure class="product-photo"><img src="${attr(note.image_url)}" alt="${attr(note.image_alt || note.product_name)}" loading="eager" decoding="async"></figure>` : '';
  const surfaces = cleanArray(note.surfaces).length ? `<div class="surface-list">${note.surfaces.map((x) => `<div class="surface-item"><span>${esc(x.emoji || '🧪')}</span><div><div class="surface-name">${esc(x.name)}</div><div class="surface-note">${esc(x.note)}</div></div></div>`).join('')}</div>` : '';
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: `${note.title} | Remy's Lab`, description: note.description, canonical, type: 'article', schema: schemas })}</head><body>${GTM_BODY}${nav('notes')}<main><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="/blog/">Lab Notes</a><span>›</span><span>${esc(note.product_name)}</span></nav><div class="post-meta"><span class="meta-pill">${esc(note.category)}</span><span class="meta-pill result">${esc(resultLabel(note.lab_result))}</span><span class="meta-pill">${esc(longDate(note.date))}</span></div><h1>${esc(note.title)}</h1><p class="post-lede">${esc(note.lede)}</p>${productPhoto}<div class="verdict"><span class="verdict-icon">${note.lab_result === 'testing' ? '🧪' : note.lab_result === 'pass' ? '↩' : '🦴'}</span><div><strong>${esc(note.verdict_title)}</strong><p>${esc(note.verdict_text)}</p></div></div>${cta(note, 'blog_post_top')}${codeBox(note)}<div class="post-body"><h2>What we tested</h2>${markdown(note.what_we_tested)}${surfaces}<h2>What worked</h2>${markdown(note.what_worked)}<h2>What did not work</h2>${markdown(note.what_didnt_work)}<h2>Remy's take</h2>${markdown(note.remys_take)}<h2>Worth buying?</h2>${markdown(note.worth_buying)}</div>${cta(note, 'blog_post_bottom')}${faqHtml(note.faqs)}<p class="disclosure">Some links may be affiliate links. If you buy through one, Remy's Lab may earn a small commission at no extra cost to you. <a href="/disclaimer.html">Full disclosure</a>.</p></div></main>${footer()}<script src="/assets/js/affiliate-tracking.js"></script></body></html>`;
}

function renderBlogIndex(notes) {
  const cats = ['Walk Gear', 'Toys', 'Treats', 'Cleaning', 'Health', 'Accessories'];
  const cards = notes.map((n) => `<a class="sticky ${attr(n.note_color || 'green')}" href="/blog/${attr(n.slug)}.html" data-filter-card data-category="${attr(categorySlug(n.category))}" data-search="${attr([n.title, n.product_name, n.category, n.card_summary].join(' '))}"><span class="tape"></span><span class="sticky-cat">${esc(n.category)}</span><span class="sticky-title">${esc(n.product_name)}</span><span class="sticky-summary">${esc(n.card_summary)}</span><span class="sticky-footer"><span class="result-badge">${esc(resultLabel(n.lab_result))}</span><span class="sticky-date">${esc(shortDate(n.date))}</span></span></a>`).join('');
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: `Lab Notes | Remy's Lab`, description: 'Written test notes after Remy actually uses the stuff. Honest takes on dog gear, cleaning tools, treats, toys, and more.', canonical: SITE + '/blog/' })}</head><body>${GTM_BODY}${nav('notes')}<main><section class="clipboard"><div class="clipboard-paper"><div class="hero-inner"><div class="eyebrow">Remy's Lab · Test reports</div><h1>Lab Notes</h1><p class="hero-sub">Written after Remy actually uses the stuff. Honest takes, no fluff.</p><div class="hero-stats"><span class="hero-stat">${notes.length} ${notes.length === 1 ? 'test' : 'tests'} filed</span><span class="hero-pill"><i></i> Active testing</span></div></div></div></section><section class="controls"><div class="controls-inner"><div class="search-row"><svg width="15" height="15" viewBox="0 0 15 15" fill="none"><path d="M10 6.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zm-.666 3.42a4.5 4.5 0 1 1 .707-.707l2.873 2.872a.5.5 0 1 1-.707.707L9.334 9.92z" fill="currentColor"/></svg><input class="search-input" id="contentSearch" type="search" placeholder="Search lab notes..." aria-label="Search lab notes"></div><div class="filter-bar"><button class="filter-pill active" data-filter="all">All Notes</button>${cats.map((c) => `<button class="filter-pill" data-filter="${categorySlug(c)}">${esc(c)}</button>`).join('')}</div></div></section><section class="board"><p class="results-label" id="resultsLabel"></p>${cards}<div class="empty-state" id="emptyState" style="display:none">No matching test notes yet. Remy's working on it.</div></section></main>${footer()}<script src="/assets/js/content-filters.js"></script></body></html>`;
}

function renderGuideIndex(guides) {
  const cats = ['Cleaning', 'Walk Gear', 'Toys', 'Treats', 'Everyday Dog Life'];
  const cards = guides.map((g) => `<a class="guide-card" href="/guides/${attr(g.slug)}.html" data-filter-card data-category="${attr(categorySlug(g.category))}" data-search="${attr([g.title, g.category, g.card_summary].join(' '))}"><span class="guide-cat">${esc(g.category)} guide</span><h2>${esc(g.title)}</h2><p>${esc(g.card_summary)}</p><span class="read">Read the guide →</span></a>`).join('');
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: `Dog Owner Guides | Remy's Lab`, description: 'Useful dog owner guides from Remys Lab, with simple answers, honest notes, and links to related products we have actually tested.', canonical: SITE + '/guides/' })}</head><body>${GTM_BODY}${nav('guides')}<main><section class="clipboard"><div class="clipboard-paper"><div class="hero-inner"><div class="eyebrow">Remy's Lab · Dog owner answers</div><h1>Dog Owner Guides</h1><p class="hero-sub">Bigger dog owner topics. We keep these limited so they do not overlap with Lab Notes.</p><div class="hero-stats"><span class="hero-stat">${guides.length} ${guides.length === 1 ? 'guide' : 'guides'} filed</span><span class="hero-pill"><i></i> Practical notes</span></div></div></div></section><section class="controls"><div class="controls-inner"><div class="search-row"><svg width="15" height="15" viewBox="0 0 15 15" fill="none"><path d="M10 6.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0zm-.666 3.42a4.5 4.5 0 1 1 .707-.707l2.873 2.872a.5.5 0 1 1-.707.707L9.334 9.92z" fill="currentColor"/></svg><input class="search-input" id="contentSearch" type="search" placeholder="Search dog owner guides..." aria-label="Search guides"></div><div class="filter-bar"><button class="filter-pill active" data-filter="all">All Guides</button>${cats.map((c) => `<button class="filter-pill" data-filter="${categorySlug(c)}">${esc(c)}</button>`).join('')}</div></div></section><section class="guide-grid"><p class="results-label" id="resultsLabel"></p>${cards}<div class="empty-state" id="emptyState" style="${guides.length ? 'display:none' : ''}">${guides.length ? 'No matching guides yet.' : 'The guide shelf is ready. Publish the first guide through the CMS when you are ready.'}</div></section></main>${footer()}<script src="/assets/js/content-filters.js"></script></body></html>`;
}

function renderGuide(guide, notesBySlug) {
  const canonical = `${SITE}/guides/${guide.slug}.html`;
  const schemas = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: guide.title, description: guide.description, datePublished: guide.date, dateModified: guide.date, author: { '@type': 'Organization', name: "Remy's Lab", url: SITE }, publisher: { '@type': 'Organization', name: "Remy's Lab", url: SITE, logo: { '@type': 'ImageObject', url: `${SITE}/assets/logos/remys-lab-logo-science-dog-transparent-v2.png` } }, mainEntityOfPage: { '@type': 'WebPage', '@id': canonical } },
    breadcrumb([{ name: 'Home', item: SITE + '/' }, { name: 'Guides', item: SITE + '/guides/' }, { name: guide.title, item: canonical }]),
    faqSchema(guide.faqs),
  ];
  const related = cleanArray(guide.related_lab_notes).map((slug) => notesBySlug[slug]).filter(Boolean);
  const relatedHtml = related.length ? `<section class="related"><h2>Related Lab Notes</h2><div class="related-grid">${related.map((n) => `<a class="related-card" href="/blog/${attr(n.slug)}.html"><strong>${esc(n.product_name)}</strong><p>${esc(n.card_summary)}</p></a>`).join('')}</div></section>` : '';
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: `${guide.title} | Remy's Lab`, description: guide.description, canonical, type: 'article', schema: schemas })}</head><body>${GTM_BODY}${nav('guides')}<main><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="/guides/">Guides</a><span>›</span><span>${esc(guide.title)}</span></nav><div class="post-meta"><span class="meta-pill">${esc(guide.category)} guide</span><span class="meta-pill">${esc(longDate(guide.date))}</span></div><h1>${esc(guide.title)}</h1><div class="quick-answer"><strong>Quick answer</strong><p>${esc(guide.quick_answer)}</p></div><div class="post-body">${markdown(guide.body)}</div>${relatedHtml}${faqHtml(guide.faqs)}<p class="disclosure">Some related Lab Notes may include affiliate links. If you buy through one, Remy's Lab may earn a small commission at no extra cost to you. <a href="/disclaimer.html">Full disclosure</a>.</p></div></main>${footer()}</body></html>`;
}

function partnerLogo(partner) {
  if (partner.logo_url) return `<span class="partner-page-logo"><img src="${attr(partner.logo_url)}" alt="${attr(partner.logo_alt || partner.brand_name)}" loading="lazy" decoding="async"></span>`;
  return `<span class="partner-page-logo text-logo">${esc(partner.brand_name.charAt(0))}</span>`;
}

function partnerButtons(partner, placement) {
  const url = partner.affiliate_url || partner.website_url;
  return `<div class="partner-actions"><button class="copy-btn coupon-copy" type="button" data-code="${attr(partner.coupon_code)}" data-product="${attr(partner.brand_name)}" data-category="partner_store" data-placement="${attr(placement)}">Grab code</button><a class="buy-btn affiliate-link" href="${attr(url)}" target="_blank" rel="nofollow sponsored" ${partnerTrackingAttrs(partner, placement)}>${partner.affiliate_url ? 'Visit brand site' : 'Visit brand site'}</a></div>`;
}

function renderPartnerIndex(partners) {
  const canonical = `${SITE}/partners/`;
  const schema = [
    { '@context': 'https://schema.org', '@type': 'CollectionPage', name: "Remy's Lab Partner Codes", description: 'Current dog product partner codes from Remys Lab.', url: canonical, isPartOf: { '@type': 'WebSite', name: "Remy's Lab", url: SITE + '/' } },
    { '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: partners.map((p, i) => ({ '@type': 'ListItem', position: i + 1, name: p.brand_name, url: `${SITE}/partners/${p.slug}/` })) },
    faqSchema(partners.map((p) => ({ question: `What is the Remy's Lab ${p.brand_name} code?`, answer: `Use code ${p.coupon_code} for ${p.user_discount} at ${p.brand_name}.` }))),
  ];
  const cards = partners.map((p) => `<article class="partner-card" data-filter-card data-category="${attr(categorySlug(p.category))}" data-search="${attr([p.brand_name, p.coupon_code, p.category, p.short_summary].join(' '))}">${partnerLogo(p)}<div class="partner-card-copy"><span class="guide-cat">${esc(p.category)}</span><h2><a href="/partners/${attr(p.slug)}/">${esc(p.brand_name)}</a></h2><p>${esc(p.short_summary)}</p><div class="code-inline"><span>${esc(p.coupon_code)}</span><strong>${esc(p.user_discount)}</strong></div></div>${partnerButtons(p, 'partners_hub')}</article>`).join('');
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: "Remy's Lab Partner Codes | Dog Product Discounts", description: 'Current Remys Lab partner codes for Pack Leashes, Brooks & Roo, and Pupford. Grab the code, read the notes, and use it only if it helps.', canonical, schema })}</head><body>${GTM_BODY}${nav('partners')}<main><section class="clipboard"><div class="clipboard-paper"><div class="hero-inner"><div class="eyebrow">Remy's Lab · Partner codes</div><h1>Remy's Lab Partner Codes</h1><p class="hero-sub">Codes from brands we currently work with. We may earn a commission, but the notes stay honest.</p><div class="hero-stats"><span class="hero-stat">${partners.length} current partners</span><span class="hero-pill"><i></i> Codes live</span></div></div></div></section><section class="guide-grid partner-grid"><div class="quick-answer page-answer"><strong>Quick answer</strong><p>Current Remy's Lab partner codes are REMYSLAB20 for Pack Leashes, REMYSLAB15 for Brooks & Roo, and REMYSLAB15 for Pupford. Use a code if it helps, no pressure.</p></div>${cards}</section></main>${footer()}<script src="/assets/js/affiliate-tracking.js"></script></body></html>`;
}

function renderPartner(partner, notesBySlug) {
  const canonical = `${SITE}/partners/${partner.slug}/`;
  const related = cleanArray(partner.related_lab_notes).map((slug) => notesBySlug[slug]).filter(Boolean);
  const relatedHtml = related.length ? `<section class="related"><h2>Related Lab Notes</h2><div class="related-grid">${related.map((n) => `<a class="related-card" href="/blog/${attr(n.slug)}.html"><strong>${esc(n.product_name)}</strong><p>${esc(n.card_summary)}</p></a>`).join('')}</div></section>` : `<section class="related"><h2>Related Lab Notes</h2><div class="related-grid"><div class="related-card"><strong>More test notes coming</strong><p>We will add specific product notes after Remy actually tests more from ${esc(partner.brand_name)}.</p></div></div></section>`;
  const schema = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: partner.title, description: partner.description, datePublished: partner.date, dateModified: partner.date, author: { '@type': 'Organization', name: "Remy's Lab", url: SITE }, publisher: { '@type': 'Organization', name: "Remy's Lab", url: SITE, logo: { '@type': 'ImageObject', url: `${SITE}/assets/logos/remys-lab-logo-science-dog-transparent-v2.png` } }, about: { '@type': 'Brand', name: partner.brand_name, url: partner.website_url }, mainEntityOfPage: { '@type': 'WebPage', '@id': canonical } },
    breadcrumb([{ name: 'Home', item: SITE + '/' }, { name: 'Partners', item: SITE + '/partners/' }, { name: partner.brand_name, item: canonical }]),
    faqSchema(partner.faqs),
  ];
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: `${partner.brand_name} Code ${partner.coupon_code} | Remy's Lab`, description: partner.description, canonical, type: 'article', schema })}</head><body>${GTM_BODY}${nav('partners')}<main><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="/partners/">Partners</a><span>›</span><span>${esc(partner.brand_name)}</span></nav><div class="partner-hero-card">${partnerLogo(partner)}<div><div class="post-meta"><span class="meta-pill">${esc(partner.category)}</span><span class="meta-pill result">Current partner</span></div><h1>${esc(partner.brand_name)} Code ${esc(partner.coupon_code)}</h1><p class="post-lede">${esc(partner.quick_answer)}</p><div class="code-inline big"><span>${esc(partner.coupon_code)}</span><strong>${esc(partner.user_discount)}</strong></div>${partnerButtons(partner, 'partner_page_top')}</div></div><div class="post-body"><h2>What ${esc(partner.brand_name)} sells</h2><p>${esc(partner.what_brand_sells)}</p><h2>What Remy is testing</h2><p>${esc(partner.what_remy_testing)}</p><h2>What we like so far</h2><p>${esc(partner.what_we_like)}</p><h2>What we are watching</h2><p>${esc(partner.watch_out_for)}</p><h2>Who this makes sense for</h2><p>${esc(partner.best_fit)}</p></div>${relatedHtml}<div class="code-box"><div><strong>Code: ${esc(partner.coupon_code)}</strong><p>${esc(partner.user_discount)} at ${esc(partner.brand_name)}. Use it if you buy.</p></div>${partnerButtons(partner, 'partner_page_bottom')}</div>${faqHtml(partner.faqs)}<p class="disclosure">Remy's Lab may earn a commission if you use this link or code. We only want the page to be useful, so the notes stay based on what we actually see with Remy. <a href="/disclaimer.html">Full disclosure</a>.</p></div></main>${footer()}<script src="/assets/js/affiliate-tracking.js"></script></body></html>`;
}

function faqEntryLinks(entry, partnersBySlug, notesBySlug) {
  const noteLinks = cleanArray(entry.related_lab_notes).map((slug) => notesBySlug[slug]).filter(Boolean).map((n) => `<a href="/blog/${attr(n.slug)}.html">${esc(n.product_name)}</a>`).join('');
  const partner = entry.related_partner ? partnersBySlug[entry.related_partner] : null;
  const partnerLink = partner ? `<a href="/partners/${attr(partner.slug)}/">${esc(partner.brand_name)} code ${esc(partner.coupon_code)}</a>` : '';
  if (!noteLinks && !partnerLink) return '';
  return `<div class="faq-links">${noteLinks ? `<span>Related test: ${noteLinks}</span>` : ''}${partnerLink ? `<span>Helpful partner: ${partnerLink}</span>` : ''}</div>`;
}

function renderFaqIndex(categories) {
  const canonical = `${SITE}/dog-product-faq/`;
  const total = categories.reduce((sum, c) => sum + cleanArray(c.entries).length, 0);
  const schema = [
    { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Dog Product FAQ', description: 'Quick answers to common dog product questions from Remys Lab.', url: canonical, isPartOf: { '@type': 'WebSite', name: "Remy's Lab", url: SITE + '/' } },
    { '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: categories.map((c, i) => ({ '@type': 'ListItem', position: i + 1, name: c.title, url: `${SITE}/dog-product-faq/${c.slug}/` })) },
  ];
  const cards = categories.map((c) => `<a class="guide-card faq-category-card" href="/dog-product-faq/${attr(c.slug)}/"><span class="guide-cat">${cleanArray(c.entries).length} answers</span><h2>${esc(c.title)}</h2><p>${esc(c.intro || c.description)}</p><span class="read">Open FAQ →</span></a>`).join('');
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: "Dog Product FAQ | Remy's Lab", description: 'Quick answers to dog product questions about leashes, training treats, chews, toys, accessories, and cleanup tools from Remys Lab.', canonical, schema })}</head><body>${GTM_BODY}${nav('faq')}<main><section class="clipboard"><div class="clipboard-paper"><div class="hero-inner"><div class="eyebrow">Remy's Lab · Quick answers</div><h1>Dog Product FAQ</h1><p class="hero-sub">Short answers for dog product questions we run into while testing stuff with Remy.</p><div class="hero-stats"><span class="hero-stat">${total} answers filed</span><span class="hero-pill"><i></i> Built for search</span></div></div></div></section><section class="guide-grid"><div class="quick-answer page-answer"><strong>How this section works</strong><p>FAQ pages handle the smaller Google and AI search questions. Lab Notes stay for real product tests. Partner pages stay for codes and brand details.</p></div>${cards}</section></main>${footer()}</body></html>`;
}

function renderFaqCategory(category, partnersBySlug, notesBySlug) {
  const canonical = `${SITE}/dog-product-faq/${category.slug}/`;
  const entries = cleanArray(category.entries);
  const schema = [
    { '@context': 'https://schema.org', '@type': 'Article', headline: category.title, description: category.description, datePublished: category.date, dateModified: category.date, author: { '@type': 'Organization', name: "Remy's Lab", url: SITE }, publisher: { '@type': 'Organization', name: "Remy's Lab", url: SITE, logo: { '@type': 'ImageObject', url: `${SITE}/assets/logos/remys-lab-logo-science-dog-transparent-v2.png` } }, mainEntityOfPage: { '@type': 'WebPage', '@id': canonical } },
    breadcrumb([{ name: 'Home', item: SITE + '/' }, { name: 'Dog Product FAQ', item: SITE + '/dog-product-faq/' }, { name: category.title, item: canonical }]),
    faqSchema(entries),
  ];
  const faqBlocks = entries.map((entry) => `<article class="faq-answer-card" id="${attr(categorySlug(entry.question))}"><h2>${esc(entry.question)}</h2><p>${esc(entry.answer)}</p>${faqEntryLinks(entry, partnersBySlug, notesBySlug)}</article>`).join('');
  return `<!DOCTYPE html><html lang="en"><head>${GENERATED}${head({ title: `${category.title} | Remy's Lab`, description: category.description, canonical, type: 'article', schema })}</head><body>${GTM_BODY}${nav('faq')}<main><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><a href="/dog-product-faq/">Dog Product FAQ</a><span>›</span><span>${esc(category.title)}</span></nav><div class="post-meta"><span class="meta-pill">${esc(category.category || 'FAQ')}</span><span class="meta-pill">${entries.length} answers</span></div><h1>${esc(category.title)}</h1><p class="post-lede">${esc(category.intro || category.description)}</p><section class="faq-answer-list">${faqBlocks}</section><p class="disclosure">These are general dog product notes from Remy's Lab, not veterinary advice. Some related pages may include affiliate links. <a href="/disclaimer.html">Full disclosure</a>.</p></div></main>${footer()}</body></html>`;
}

function sitemap(notes, guides, partners, faqCategories) {
  const pages = [
    ['/', TODAY, 'weekly', '1.0'],
    ['/partners/', firstDate(partners), 'weekly', '0.9'],
    ['/blog/', firstDate(notes), 'weekly', '0.9'],
    ['/dog-product-faq/', firstDate(faqCategories), 'weekly', '0.9'],
    ['/guides/', firstDate(guides), 'monthly', '0.6'],
    ...partners.map((p) => [`/partners/${p.slug}/`, p.date, 'monthly', '0.85']),
    ...notes.map((n) => [`/blog/${n.slug}.html`, n.date, 'monthly', '0.8']),
    ...faqCategories.map((c) => [`/dog-product-faq/${c.slug}/`, c.date, 'monthly', '0.8']),
    ...guides.map((g) => [`/guides/${g.slug}.html`, g.date, 'monthly', '0.7']),
    ['/privacy.html', '2026-05-29', 'yearly', '0.3'],
    ['/terms.html', '2026-05-29', 'yearly', '0.3'],
    ['/disclaimer.html', '2026-05-29', 'yearly', '0.3'],
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(([url, lastmod, freq, priority]) => `  <url><loc>${SITE}${url}</loc><lastmod>${lastmod}</lastmod><changefreq>${freq}</changefreq><priority>${priority}</priority></url>`).join('\n')}\n</urlset>\n`;
}

function llms(notes, guides, partners, faqCategories) {
  return `# Remy's Lab\n\n> Dog products tested by an actual Lab.\n\nRemy's Lab is a TikTok connected dog product testing brand built around Remy, a yellow Labrador. The site helps dog owners find product notes, partner links, discount codes, and quick dog product answers without a hard sell.\n\n## Pages\n\n- [Remy's Lab home](${SITE}/): Simple TikTok landing page with current codes, product links, Lab Notes, and affiliate disclosure.\n- [Partner Codes](${SITE}/partners/): Current Remy's Lab partner codes and partner pages.\n- [Lab Notes](${SITE}/blog/): Written notes after Remy actually uses a product.\n- [Dog Product FAQ](${SITE}/dog-product-faq/): Short answers to common dog product questions, grouped by category.\n- [Dog Owner Guides](${SITE}/guides/): Larger evergreen dog owner topics.\n\n## Current partner brands\n\n${partners.map((p) => `- [${p.brand_name}](${SITE}/partners/${p.slug}/): Use code ${p.coupon_code} for ${p.user_discount}.`).join('\n')}\n\n## Lab Notes\n\n${notes.map((n) => `- [${n.title}](${SITE}/blog/${n.slug}.html): ${n.card_summary}`).join('\n') || '- No Lab Notes are currently published.'}\n\n## Dog Product FAQ Categories\n\n${faqCategories.map((c) => `- [${c.title}](${SITE}/dog-product-faq/${c.slug}/): ${c.description}`).join('\n') || '- No Dog Product FAQ pages are currently published.'}\n\n## Dog Owner Guides\n\n${guides.map((g) => `- [${g.title}](${SITE}/guides/${g.slug}.html): ${g.card_summary}`).join('\n') || '- No Dog Owner Guides are currently published.'}\n\n## Social\n\n- TikTok: https://www.tiktok.com/@remy.lab\n\n## Affiliate disclosure\n\nSome links may be affiliate links. If a visitor uses one, Remy's Lab may earn a commission. That does not change which products are listed or what gets written about them.\n`;
}

function main() {
  ensure('blog'); ensure('guides'); ensure('partners'); ensure('dog-product-faq');
  cleanGeneratedTree('blog'); cleanGeneratedTree('guides'); cleanGeneratedTree('partners'); cleanGeneratedTree('dog-product-faq');
  const notes = readDir('content/lab-notes');
  const guides = readDir('content/guides');
  const partners = readDir('content/partners');
  const faqCategories = readDir('content/faq-categories');
  const notesBySlug = Object.fromEntries(notes.map((n) => [n.slug, n]));
  const partnersBySlug = Object.fromEntries(partners.map((p) => [p.slug, p]));
  notes.forEach((n) => write(`blog/${n.slug}.html`, renderLabNote(n)));
  guides.forEach((g) => write(`guides/${g.slug}.html`, renderGuide(g, notesBySlug)));
  partners.forEach((p) => write(`partners/${p.slug}/index.html`, renderPartner(p, notesBySlug)));
  faqCategories.forEach((c) => write(`dog-product-faq/${c.slug}/index.html`, renderFaqCategory(c, partnersBySlug, notesBySlug)));
  write('blog/index.html', renderBlogIndex(notes));
  write('guides/index.html', renderGuideIndex(guides));
  write('partners/index.html', renderPartnerIndex(partners));
  write('dog-product-faq/index.html', renderFaqIndex(faqCategories));
  write('sitemap.xml', sitemap(notes, guides, partners, faqCategories));
  write('llms.txt', llms(notes, guides, partners, faqCategories));
  console.log(`Built ${notes.length} Lab Notes, ${guides.length} Guides, ${partners.length} Partners, and ${faqCategories.length} FAQ categories.`);
}

main();
